# Generated by Django 3.1.7 on 2021-06-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
