# Generated by Django 3.1.7 on 2021-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210606_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.FileField(default=None, upload_to='profile_pics'),
        ),
    ]
